kind: pipeline
type: docker
name: default

steps:
  - name: update
    image: debian:stable-slim
    commands:
      - apt update && apt install -y curl git jq
      - ./update.sh
  - name: push
    image: appleboy/drone-git-push
    settings:
      remote: git@github.com:ServiusHack/filestash.git
      branch: master
      local_ref: master
      force: true
      ssh_key:
        from_secret: PUSH_SSH_KEY
